### ISSUE TITLE
Terrain Options Add Collider doesn't work

### ISSUE THREAD

**Issue by citizen12** [mapbox/mapbox-unity-sdk#1234]
No colliders are added to the Mapbox-generated terrain Game Objects, even when you ask for them.

* Unity version: 2018.3.0f2
  * Scripting Runtime Version: .NET 4.x Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level:  .NET Standard 2.0
* Mapbox SDK version: 2.0.0 (from website)
* The platform you're building to: Android
* A description of what you're trying to do: Get colliders on terrain
* Steps to recreate the bug if appropriate: In AstronautGame or WorldScale AR example scenes, check "Add Collider" on Terrain options for the map.  Create a game object with a rigidbody and collider and observe it fall through the terrain.  Also note that there is no Mesh Collider added to the terrain objects in the scene.

Expected terrain GameObjects to have Mesh Colliders when Add Collider was chosen.

**Comment by citizen12** [comment]
Apparently, it does not work when you have your elevation layer type set to Flat Terrain.

**Comment by siyuan-li** [comment]
I met the same problem. At this moment, It seems that [Possible bug in CitySimulatorMap #1185](https://github.com/mapbox/mapbox-unity-sdk/issues/1185) didn't provide any solution to this problem yet. 
Here is my investigation. After hitting play on unity, then uncheck and check back "Add Collider", I found the mesh colliders were added to all the vector tiles successfully. 
My guess is that Mapbox SDK does not execute `public override void UpdateProperty(UnityTile tile)` to check whether "Add Collider" was checked in initialization stage.  And this function is located at "Mapbox/Unity/DataContainers/TerrainColliderOptions.cs".

**Comment by tab1887** [comment]
I'm facing the same issue. Has a fix been provided yet? I can't find any commit with this issue number.

**Comment by DianaDI** [comment]
I am facing still the same issue. Please help to resolve.

**Comment by brnkhy** [comment]
Hey @citizen12, @siyuan-li, @tab1887, @DianaDI 
ticket was closed so I didn't see it for a long time.
Checked this today and I think this should fix the issue; https://github.com/mapbox/mapbox-unity-sdk/tree/flatTerrainColliderFix

**Comment by DianaDI** [comment]
@brnkhy Thanks a lot! Actually, I made a temporary solution by adding "invisible" terrain with a collider.

**Comment by brnkhy** [comment]
@DianaDI very happy to hear that! 
Also that might even be better if it works for you. One box collider for whole terrain. but of course we have to think about many other stuff like, loading/unloading tile etc etc. so I had to go with per-tile for now.

**Comment by yosun** [comment]
Still seems to be an issue with latest Mapbox Unity SDK... flat terrain has no colliders

**Comment by yosun** [comment]
Workaround - lowpoly terrain, exaggeration factor 0

**Comment by brnkhy** [comment]
Hey @yosun!
This commit should fix it; https://github.com/mapbox/mapbox-unity-sdk/commit/79664cc3329e7525344bb713fd21d167b55febcb
We haven't had a release after that so it is broken in package but should be fixed in dev branch.

**Comment by yosun** [comment]
> Hey @yosun!
> This commit should fix it; [79664cc](https://github.com/mapbox/mapbox-unity-sdk/commit/79664cc3329e7525344bb713fd21d167b55febcb)
> We haven't had a release after that so it is broken in package but should be fixed in dev branch.

wow that has been over a year with no updates to the release branch! oh no - is Unity support being deprecated?

**Comment by brnkhy** [comment]
@yosun last release was 2019 October I believe and I have been pushing fixes to dev branch this year but got tied up with some bigger stuff at the moment (performance improvements). So we are active at the moment :)

**Comment by sgtrusty** [comment]
Still broken ... Why is this closed? Using yosun's solution meanwhile.

**Comment by sethHex** [comment]
> 

this is still not working?
