### ISSUE TITLE
Mapbox Studio custom style not refreshing in Unity

### ISSUE THREAD

**Issue by AmberElferink** [mapbox/mapbox-unity-sdk#1364]
* Unity version: Unity 2019.1.2f1
  * Scripting Runtime Version:  .NET 4.x Equivalent
  * Scripting Backend: Mono
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: v2.0.0
* The platform you're building to: PC
* A description of what you're trying to do: 
I am trying to add custom textures via Mapbox Studio, adjust them and reload the tiles in Unity.
* Steps to recreate the bug if appropriate: 
1. Make a new Unity Project
2. Import the Mapbox Package via Assets > Import Package > Custom Package.
3. Drag the CitySimulater example from Mapbox/Core/Examples/0_Prefab to the hierarchy.
4. Add a custom texture style url:
- Click CitySimulatorMap in the Hierarchy.
- Under Image, place the style url from Mapbox Studio. In my case: mapbox://styles/amberelferink/cjvgfsx9g2nmi1fma4x94ks7g
5.  I use the coordinates: 51.892762, 5.850779
6. Start the Simulation. The custom textures load. Stop the simulation
7. Click another pattern for the grass for example in Mapbox Studio
8. Click Publish.
9. In Unity: Mapbox > Clear Cache
10. Start Simulation

**Expected result:** Loads new Patterned texture.
**Actual result:** Shows the previous loaded texture.
- When adjusting the West, North, East, South Extent Options, the new texture loads correctly in the new tiles.
- When making a completely new Unity project, reimporting the asset, etc, it works the first time only again.
- If I select Mapbox Streets instead of Custom for the Style Url in Unity, it shows Mapbox Streets correctly. If I switch back to Custom, my old map is still there.

What can I do to fix this? It is really important that it loads on those same coordinates.

**Comment by AmberElferink** [comment]
In case someone thinks it could have to do with my settings, here are the settings I currently use for the Abstract Map.
![image](https://user-images.githubusercontent.com/32518317/57683715-90217700-7634-11e9-99e5-f0fb10be3b61.png)
![image](https://user-images.githubusercontent.com/32518317/57683732-9879b200-7634-11e9-9f16-236253aaa326.png)

**Comment by brnkhy** [comment]
@AmberElferink It definitely sounds like a cache issue but I saw you clear it after mapid changes. I wonder if it might be server side caching for a short time? Or maybe something bugged out in our caching code. I'll try it out, thanks for the ticket 🙏

**Comment by AmberElferink** [comment]
@brnkhy Yes, I thought so too. However:
Even after shutting down my computer, having weekend, and retrying on monday, it still is not updated. It is persistent somehow. 

I also checked if the local cache is truly cleared:

In Appdata/"MyProjectName"/cache
the cache.db shows around 900 kb before clearing cache.
After pressing "Clear cache" it is only 10 kb. At least it removes something, but I don't know if that is all that must be cleared by that button of course. 

I would be really happy if you got back to me :). It is a function that is a must have in our project, so if you have any clue about how to fix it, that would be amazing. It has been holding up development for a few days now. Thanks for looking into this!

**Comment by brnkhy** [comment]
@AmberElferink that looks like an sdk code issue then. Very strange. I think you can delete that cache file and it'll be recreated by the way, have you tried that? But I'm not sure what it would mean/show.

`It is a function that is a must have in our project` 
just to understand better, you mean for development right? This shouldn't effect final product I guess? Or are you planning to actively change maps maybe?

**Comment by AmberElferink** [comment]
@brnkhy, I closed down Unity and deleted the cache.db. When I started Unity and pressed start, it still shows yesterdays pattern. I think it is maybe cached somewhere else, but I'm not familiar enough with the code to figure out where. I tried that for multiple hours.

> just to understand better, you mean for development right? This shouldn't effect final product I guess? Or are you planning to actively change maps maybe?

Actually it is important for our final product. We use real locations in many of our projects. We want to make an editor which customers can use to place objects and customize them. The map textures are actually the most important aspect of this. It is the must have of this project, that is why it is so important for this to work for us.

**Comment by AmberElferink** [comment]
@brnkhy Did you manage to take a look at it yet? I'm curious if this problem is only on my side. My next step would be make a very colourful map and generate a 3D mesh over it with my own materials. That however, will take many, many hours to implement. 

Do you think there is a possibility this could be fixed before I should resort to that method? Or don't you think this is going to be fixed these coming few weeks. In that case I should get started.

This is not ment to rush you. I would simply like to know if I should get started on this :)

**Comment by brnkhy** [comment]
@AmberElferink I haven't had a chance to look at it so far but I'll try until monday. 
I can't suggest anything at the moment as I have no idea what's wrong really :( sorry about it 
I promise I'll check it asap though.

**Comment by brnkhy** [comment]
I checked this today, I'm pretty sure this is some server side caching and considering how raster tiles area heavy to create and serv, I think it's a reasonable guess. I'll ask to my colleagues this week.

**Comment by AmberElferink** [comment]
Thank you for taking a look at it. Server side could be, although I find it weird that if I make a new project and reimport all the assets, it does load the new pattern the first time. If it would be only on the server side, I'm not sure if that makes sense. Hence why I decided to make a github issue on the Unity side.
It is in one of the two of course, so it's still certainly an option. Thank you for your quick response!

**Comment by AmberElferink** [comment]
@brnkhy Hey, I double checked and I don't see a how this can be due to a problem on the server and not in Unity. The entire map works perfectly, except for the tiny piece I need to have loaded in Unity. I made a video to explain the behavior. Can you check the video (38 seconds)? 
https://streamable.com/i9ch2
Sorry for the crappy sound. My microphone is a potato. 
Let me know what you think :).

**Comment by brnkhy** [comment]
@AmberElferink that's interesting. Problem is I'm getting the old texture even when I delete the sql cache file, that alone made me think it was server side caching. Because unity cannot be keeping those textures anywhere else I thought.
In your video, it looks like a cache reset failure problem. I'll try again and let you know.

**Comment by AmberElferink** [comment]
Yes, for me that is exactly the same. I can delete the cache.db in the Appdata however much I want, but the texture remains, I manually checked that that file gets filled and removed by the Clear Cache button. That is why I'm confused as well. At least that makes two of us now.

**Comment by AmberElferink** [comment]
Update: due to this and some other issues with mapbox, I decided to buy Online Maps. Surprise, loading the mapbox custom design in there, gives exactly the same behaviour with loading the tiles, even with caching completely disabled. It might be server related after all? I don't know anymore at this point.

**Comment by miguelmonteroboiko** [comment]
Hey! I've had the same problem, and my solution just is to Duplicate the map and link the URL.

**Comment by AmberElferink** [comment]
Hi Miguel,

Yes that does work, but you must do it every single time you make a change. The idea of my application was that customers could load customized maps automatically, so duplicating every time is not an option. 
I have now written a shader that can place a texture over each color on the tile. It does the job but if mapbox would have worked it would have saved many days of work. I'm sure I'm not the only one who desperately needs this functionality.

**Comment by brnkhy** [comment]
I'll try to find someone who knows more about server side stuff to ask about this, sorry for the long wait :(

**Comment by atripathi-mb** [comment]
@AmberElferink 
Two things to keep in mind. 
1. If you want to refresh tiles during runtime, please check the `Auto Refresh Cache` checkbox under setup. See Screenshot below. This will ensure that the sdk checks whether a new tile is available for the cached tiles instead of just loading from the cache. 

![image](https://user-images.githubusercontent.com/32286016/61652568-18437e80-ac6d-11e9-9ec2-890866051f05.png)

It may be better to clear cache before pulling the new style. 

2. If you make changes to the style in studio, there is a server-side caching that may take upto 15 mins to refresh the tiles. Changes might only appear after 15 mins.

**Comment by AmberElferink** [comment]
Hi atripathi,
Thank you for your reply. Your first point is a good tip for final implementation. Thank you for that, however it does not resolve the issue. In whatever way the local cache is deleted or prevented from using it, it does not refresh. 
I first thought the second point was the problem, however even after weeks(!) it still does not refresh the tiles. I think there probably is an issue in the server somewhere that prevents the online tile caches from refreshing after they have been requested.

**Comment by miguelmonteroboiko** [comment]
Ahh! Nice, you guys are amazing! This is going to save me at least some laziness jajaja

**Comment by atripathi-mb** [comment]
@AmberElferink I am not able to reproduce the issue on my end. I tried your style and at runtime tried switching between the default styles and custom style ( dark/light/satellite and yours) and get the correct result. 

![image](https://user-images.githubusercontent.com/32286016/61729735-bb0f0200-ad2c-11e9-83b9-1b29f04dcc1d.png)

Would you be able to give me some more details? The behavior you're seeing is unexpected, let's make sure we can fix the issue for you. 

Also, how did you delete the cache? Through the Mapbox-> Delete Caches menu or directly deleting the caches.db file?

**Comment by atripathi-mb** [comment]
@AmberElferink Another way to check if the tiles are updated server-side is to use the API request directly. 

eg https://api.mapbox.com/styles/v1/amberelferink/cjvgfsx9g2nmi1fma4x94ks7g/tiles/16/33833/21679?events=true&access_token=YOUR_TOKEN_HERE

**Comment by AmberElferink** [comment]
@atripathi-mb As you can read above, I have tried both clearing the cache from the menu and deleting the cache.db file directly.
I have also used the mapbox api directly via another app, which gives the same results.

I think there is a possibility you misinterpreted my problem. I doubt you can change my map via that link, so I don't think you can test it so you would get the same problem. 
The problem is no in switching between light, dark and my map. The problem is when I load my map in Unity (and stop the simulation), then change the color of the tiles in Mapbox studio, and then load exactly that same area I loaded earlier in Unity again. That is the area that won't update. I doubt you can change my map, so I think you need to make your own to test that.
If you want to help me from your side, make a new map. Assign a pattern to certain fields (I am using svg, I didn't check if that matters). Then load specific coordinates and zoom level in Unity.
Now change the pattern and publish it.
Then reload that area in Unity. Is that exact same area and zoom level updated on your side?

**Comment by walalabee** [comment]
Hello there,

I have the same problem. Has it been solved or not yet ?

Thx

**Comment by AmberElferink** [comment]
Hi @walalabee,

It has not been solved as far as I am aware. Due to this problem taking ages and the zoom that was not smooth I switched to the paid Online Maps asset. I implemented changing the color with a shader (they have a video on that). It is way less user friendly, but at least it worked. Pity they didn't fix this yet. Seems like a major issue to me.

**Comment by TiborUdvari** [comment]
I have had the same issue. It turns out it was coming from the server-side caching, during development you can share a **draft version** of the style which updates more or less directly. This fixed it for me, during the testing phase at least.

**Comment by davidnmora** [comment]
^ @TiborUdvari good workaround. Adding a `/draft` to the end of the URL worked for me in Mapbox GL JS as well. 🎊

**Comment by austinjhunt** [comment]
This unfortunately is still not resolved; using Mapbox for online campus map development for College of Charleston and updating map styles does not have any effect for an extended period of time due to server-side caching (clearing client cache doesn't resolve the issue); wondering if this is cache TTL is configurable on the Mapbox side.
