### ISSUE TITLE
Android Build Not Supported: 'MergeNativeLibsTask' Error with Empty Unity Project and Mapbox SDK 3.0.0

### ISSUE THREAD

**Issue by DallenLarson** [mapbox/mapbox-unity-sdk#1932]
When building on an empty Unity project with just this package, Unity gives: "A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction See the Console for details."

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 6000.0.0f1
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET Standard 2.1
* Mapbox SDK version: 3.0.0
* The platform you're building to: Android
* A description of what you're trying to do: I'm trying to build a simple, empty Unity project that includes this package for an Android platform.

* Steps to recreate the bug if appropriate:

- Start with a new, empty Unity project
- Import the Mapbox SDK package (version 3.0.0).
- Set the build platform to Android and attempt to build the project.

* Links to your logs are also helpful: 
[](https://docs.google.com/document/d/1mvl88fbzYhljGHSZzYNJWzeSh-cghhiQe5JboTzsIPU/edit?usp=sharing
)
Note: I’m so happy this SDK exists and grateful that someone is keeping the Unity SDK alive! I hope this is a quick fix, and I deeply appreciate all your hard work. 🙏

**Comment by DallenLarson** [comment]
If the log link doesn't show up it is: https://docs.google.com/document/d/1mvl88fbzYhljGHSZzYNJWzeSh-cghhiQe5JboTzsIPU/edit?tab=t.0

**Comment by brnkhy** [comment]
@DallenLarson @lucasgray 
OK I'm not sure if this is the issue but there's actually something big missing at the moment (and we'll fix it on a moment)
- first of all, pull the latest and get the change where I removed one setting from gradle file.
- now yes, there actually are gradle settings inside the mapbox package but it isn't applied to the build. now please copy the plugins folder inside mapbox package and put it under your projects assets folder. now your build settings should look like this (I believe it automatically detects these files as long as they are under `Plugins/Android` folder)
<img width="507" alt="Screenshot 2025-01-12 at 21 49 03" src="https://github.com/user-attachments/assets/20ba82da-c2ec-48f5-84b4-6826c80295bc" />

- now with these files in their proper places, android build worked for me. 

Please let me know if it works!

**Comment by DallenLarson** [comment]
@brnkhy Hey! Thanks so much for responding and trying to fix it! I tried all of this with a new empty project but it sadly gives me: **CommandInvokationFailure: Gradle build failed.**

Full Log:
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\6000.0.0f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\6000.0.0f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-8.4.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

**Comment by brnkhy** [comment]
@DallenLarson I'll keep looking into it but you might want to cleanup the log, I think there are some keys visible in it

**Comment by lucasgray** [comment]
Hmm.. I have a bit of a different issue. I pulled down the change and copied the gradle files. I pulled open player settings and sure enough, they were being sourced from the right files.

Once I went to build I had to step through a series of prompts that I think modified the gradle file - maybe I shouldn't have clicked confirm through these.

The build eventually failed with the same error - which is curious since I do see the `packaging` block in that gradle file. I may try again with a fresh file

<img width="644" alt="Screenshot 2025-01-13 at 7 38 07 AM" src="https://github.com/user-attachments/assets/4f00df1c-e20f-4d45-8169-c56902c2a0a9" />
<img width="629" alt="Screenshot 2025-01-13 at 7 37 54 AM" src="https://github.com/user-attachments/assets/f2b8ba1a-e908-4bc8-a29c-f8af66bf79e1" />
<img width="383" alt="Screenshot 2025-01-13 at 7 37 43 AM" src="https://github.com/user-attachments/assets/230e5bff-bd87-45c8-9c2d-281792dcb1da" />
<img width="453" alt="Screenshot 2025-01-13 at 7 37 26 AM" src="https://github.com/user-attachments/assets/5d8110d9-abee-4b29-8a0b-cc1fb815f67e" />

```
What went wrong:
Execution failed for task ':launcher:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/lucas-play/Runstrike Play/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build/intermediates/library_jni/debug/copyDebugJniLibsProjectOnly/jni/arm64-v8a/libc++_shared.so
      - /Users/lucas-play/.gradle/caches/transforms-3/e3afce06a9df19ac0a5121b6c2a25f07/transformed/jetified-common-24.0.0-beta.7/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

**Comment by brnkhy** [comment]
@lucasgray @DallenLarson I see you are both using Unity6, I did my build with 2022.3. If I remember correct 2022.3 uses gradle 7.5.1, U6 uses 8.4.
I'll try with U6 and let you know if I find anything.

**Comment by DallenLarson** [comment]
Thank you, as a heads up what worked for me was clearing the library folder and modifying the Manifest and Gradle files.

**Comment by brnkhy** [comment]
@DallenLarson oh it worked for you in the end? so settings actually work, do you remember any non project related changes in those manifest and gradle files? you can also answer in private if you prefer; baran.kahyaoglu@mapbox.com

**Comment by Jacki3** [comment]
Has anyone resolved this issue? After updating the gradle and manifest files I still recieve launcher:mergeReleaseNativeLibs error when building to Android using Unity 6 and gradle 8.4. Thank you! @brnkhy did you have any luck with using Unity 6 and the SDK?

**Comment by jungrok5** [comment]
I'm getting the same error too.

* Unity version: 6000.0.40f1
* Mapbox SDK version: 3.0.1
* Android

![Image](https://github.com/user-attachments/assets/12f9ec26-ce03-493d-a7fd-fef68e571c35)

```
* What went wrong:
Execution failed for task ':launcher:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - C:\Project\MapBoxV3\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\build\intermediates\library_jni\release\copyReleaseJniLibsProjectOnly\jni\arm64-v8a\libc++_shared.so
      - C:\Users\jungrok5\.gradle\caches\transforms-3\162bef2a1fdab3cd230f34559460ae33\transformed\jetified-common-24.10.0-daily\jni\arm64-v8a\libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

**Comment by brnkhy** [comment]
@Jacki3 @jungrok5 I think I did builds with U6 at one point but I'm normally using 2022.3 lately. I'll give it another try soon and let you know.

**Comment by jungrok5** [comment]
@brnkhy 
As you said, the Android build is successful in the 2022.3 late version, but it shows like this
![Image](https://github.com/user-attachments/assets/1c7a7054-624a-4b65-8a32-d86b05326be9)

**Comment by jungrok5** [comment]
@brnkhy 

If I add the following settings to the build.gradle file, the Android build succeeds even in Unity 6! However, I can't modify it like this every time. Is this the correct approach?

`C:\Project\MapBoxV3\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\build.gradle`
```
android {
    packagingOptions {
        exclude 'lib/arm64-v8a/libc++_shared.so'
    } 
}
```

**Comment by brnkhy** [comment]
@jungrok5 that's interesting. it looks like something we can add to `mainTemplate.gradle`, it's under the folder you copied from package to your project, can you try that?

edit: pinky 2022.3 screenshot is just a shader error, it's probably not set to use URP in that shot.

**Comment by jungrok5** [comment]
@brnkhy 

As you told me, I activated the custom Gradle settings and modified the `mainTemplate.gradle` file.

From Unity 6, if you modify it as follows instead of `packagingOptions`, it will work perfectly.

Thanks to you, I can finally develop using Mapbox in Unity 6.
Thank you so much!

![Image](https://github.com/user-attachments/assets/6c774aca-122e-47ce-a424-a93ae68779e0)

```
android {   
    packaging {
        exclude '**/libc++_shared.so'
    } 
}
```

**Comment by brnkhy** [comment]
@jungrok5 great news but there's a slight problem once more :)
you were actually supposed to copy gradle/android settings into your project as described here; https://github.com/mapbox/mapbox-unity-sdk/blob/sdk3/README.md
but I think you didn't had them?
you were able to build and didn't get any errors without those?
some dependencies are listed in those files, I wonder your setup resolved them automatically or you did get an error and didn't realize it.

**Comment by jungrok5** [comment]
@brnkhy 

I was focused on the successful build and missed copying the required files. 
When copying the files as instructed in the README, and just building, the same build error occurred. 
To resolve it, I had to set the exclude setting to mainTemplate for the build to succeed. 
However, when running on Android, the app crashed with the error 

```
2025-03-02 00:16:02.524 12771 12771 Error AndroidRuntime java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTTNSt6__ndk118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE" referenced by "/data/app/~~GnxV96BwaeOUzzGrM2S34g==/com.UnityTechnologies.Mobile3DTemplate-GYnA07GNYiXfkY0ciyQM-w==/lib/arm64/libgame.so"...
```

edit:
When using a custom AndroidManifest, this error occurs. If disabled, the error above happens.
![Image](https://github.com/user-attachments/assets/249387c8-a691-4849-ae37-62363a0ad1e4)

**Comment by brnkhy** [comment]
@jungrok5 I'm working on this, just now managed to get an android build on U6 but want to understand it a little better before sharing.

**Comment by Jacki3** [comment]
Thanks for the time you both have commited to this issue, it is greatly appreciated. 

Overriding the main gradle template and adding the android packaging options that @jungrok5 mentioned does get a build working for me but I have yet to test the behaviour on a device (this is without using any of the gradle settings that are supplied by @brnkhy). 

The cause of this error seems to stem from deprecated API usage but actually accessing those files and modifying them can be tricky due to the nature of how the package has been installed.

If the updated main gradle template fix works on a device then this is great but I fear it is not the root cause of the issue. As with prior Mapbox versions and Unity 6 (or more likely how Unity works with Android) there are issues with either duplicate classes or perhaps deprecated functionalities which seem to conflict with AndroidX; perhaps related to java? The ideal outcome is an updated plugin that does not require overriding gradle settings manually but this is a lot to ask and the fix @jungrok5 seems to be least complex route to getting an apk from Unity.

**Comment by brnkhy** [comment]
@jungrok5 @Jacki3 I'll just share what I found;
- @jungrok5 earlier mentioned build worked with that fix but **without** SDK gradle settings which was surprising to me, it really shouldn't work without the dependencies in those files. I just tested that, build works but app won't run without those settings. (please let me know if you managed to do it)
- so next, I added sdk gradle settings AND the `exclude` fix. It went better but again app crashed on launch with a library error.
- then I went ahead and add this line to `mainTemplate.gradle`
```
implementation group: 'org.chromium.net', name: 'cronet-common', version: '76.3809.111'
```
and app run as expected.

My current problem is, I don't know or understand android libraries so I'm not sure it's a correct fix to add another library.

@Jacki3 I agree it's much better if we can understand and fix the duplication issue, I'll try to investigate that as well. maybe updating other dependencies or something may work.

**Comment by jungrok5** [comment]
@brnkhy 

1. Copy the `Mapbox Unity SDK/Runtime/Plugins` folder into your project, placing it under the `Assets` folder.
2. Added `exclude` Configuration in `mainTemplate.gradle`
3. Verified the Following Settings

![Image](https://github.com/user-attachments/assets/3685d074-6299-45b7-a7d9-c45589dea9c5)

After building and deploying to the device, an error occurred:

![Image](https://github.com/user-attachments/assets/a17c33bd-7704-4912-b72c-601376e72716)

4. Unchecked `Custom Main Manifest`
The build completed successfully.
However, the app crashed upon execution.

5. Added `cronet-common` Configuration in `mainTemplate.gradle` The app still crashes on execution.

**Comment by brnkhy** [comment]
@jungrok5 `Unchecked Custom Main Manifest` I forgot to add I did this as well but glad you found out.
edit: and I even disabled `custom gradle properties template`, that also may worth trying I guess.

> Added cronet-common Configuration in mainTemplate.gradle The app still crashes on execution.

this is interesting though, I think it worked for me at that point. Can you check the logcat and find the error, I'm sure it'll be another 'can't find class x` type of thing.

**Comment by jungrok5** [comment]
@brnkhy 

This error occurs.

```
2025-03-02 16:41:45.260 27327 27327 Error AndroidRuntime java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTTNSt6__ndk118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE" referenced by "/data/app/~~MImt9PGeqTfsvbgd63kFpQ==/com.UnityTechnologies.Mobile3DTemplate-sdmjXgLOCkZW7SE6iq8ZCA==/lib/arm64/libgame.so"...
```

And the crash occurs the same way regardless of whether the `custom gradle properties template` is checked or not.

**Comment by brnkhy** [comment]
@jungrok5 I pushed a proposed fix here; https://github.com/mapbox/mapbox-unity-sdk/tree/androidUnity6
it adds a different dependency in form of google play services. fix another small bug for some web requests. removes two of the setting files and now just uses `mainTemplate.gradle`.
I was able to build and run the application without any issues on this branch.

**Comment by jungrok5** [comment]
@brnkhy 

androidUnity6 branch is giving the same error.

![Image](https://github.com/user-attachments/assets/d3bffda2-fb20-4925-b32b-176207b55684)

**Comment by brnkhy** [comment]
@jungrok5 ok I guess it can't find the library now (and somehow does on my machine),
I found a similar question here; https://stackoverflow.com/questions/70890854/2-files-found-with-path-lib-arm64-v8a-libc-shared-so-from-inputs-react-na
and according to suggestions there, 
- remove this line we added earlier;
```
packaging {
        exclude '**/libc++_shared.so'
    } 
```
- add these lines
```
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
```

so instead of `exclude` I guess we are telling gradle to pick particular one.
I tried this with success, can you give it a shot?

**Comment by jungrok5** [comment]
@brnkhy 
I already tried `pickFirst` but it didn't resolve the duplication error during the build process.

**Comment by brnkhy** [comment]
@jungrok5 I think you are right, I did a clean build in an empty folder and back to that error now.
edit: exclude still works for me by the way, interesting it doesn't for you. maybe the error you are getting with exlude (last screenshot) is a different issue.

**Comment by brnkhy** [comment]
@DallenLarson 
> as a heads up what worked for me was clearing the library folder and modifying the Manifest and Gradle files.

can you share what changes to manifest&gradle settings helped you?

**Comment by brnkhy** [comment]
it looks like adding `mainTemplate.gradle`
```
packaging {
        exclude '**/libc++_shared.so'
    } 
```
works for the duplicate library error.

I also tried adding `launcherTemplate.gradle`
```
packaging {
            jniLibs.pickFirsts.add("**/libc++_shared.so")
        }
```
and that also seems to fix the issue.

I'm not sure which one is better but I suspect both are pretty much same.

**Comment by jungrok5** [comment]
@brnkhy 
I finally got a build that runs properly on my Android device! 
The method you mentioned at the end worked! 
Thank you so much and thank you for your hard work!

**Comment by brnkhy** [comment]
@jungrok5 oh wow I wasn't expecting that :) 
you mean the `launcherTemplate.gradle` fix, right? to be honest I didn't had courage to ask you for another try after so many fails :) thank YOU very very much! 
OK I'll apply that one and push it on that fix branch, then other people can easily test it out as well.

**Comment by jungrok5** [comment]
@brnkhy 
Yes. The method of adding pickFirst here in launcherTemplate.gradle worked. If I explain the whole process, 
1. In the `integrityCheckDebugPath` branch, (https://github.com/mapbox/mapbox-unity-sdk/issues/1912)
2. Only use `mainTemplate.gradle` from the `androidUnity6` branch, 
3. Remove `exclude` from `mainTempalte.gradle`, and 
4. Add `pickFirst` to `launcherTemplate.gradle`

**Comment by brnkhy** [comment]
OK hopefully for the last time, here it is; https://github.com/mapbox/mapbox-unity-sdk/tree/androidUnity6
- checkout to branch
- follow the quickstart guide for android build (https://github.com/mapbox/mapbox-unity-sdk/blob/sdk3/README.md) and copy the plugins folder into your own project. Plugins folder will have two files now instead of three mentioned by readme.
- be sure your build settings looks like this;
<img width="713" alt="Image" src="https://github.com/user-attachments/assets/526e0876-468a-4121-9f31-ee469a1e2ed3" />

and hopefully your unity 6 & android build will work.
please let me know if it works or not 🙏

**Comment by Jacki3** [comment]
Hi all, apologies for the delay.

I can confirm that the branch @brnkhy has setup ('androidUnity6') does indeed build a runnable and working apk when the gradle settings have been copied into the project (found at 'Runtime/Plugins/Android')  This is great news - thank you for spending the time getting something that is operational!

There are a things to note:

1. Starting the app up for the first time appears to not want to load the map but closing it and opening again seems to fix this for good (not a big deal and could be permissions related).
2. Updating the launcher settings is quite a serious step to get an apk up and some devices may ask users to "scan" the application before installing which looks bad for the user and may be an issue when trying to port the app onto the Playstore or on other more security obsessed devices.

Otherwise it works and I do enjoy both the map theme (is this a public map theme?) and the astronaut walking animations. 

I will continue to investigate the cause of this issue and try to find out where there is depcreated code (or conflicts with duplicate classes) and begin to update the plugin if/when I have the time. I would suggest the Mapbox team also have an open investigation too - I have not come across many (or perhaps any) public plugins that require custom build files so perhaps this is not the most ideal solution.

Thank you!

**Comment by brnkhy** [comment]
@Jacki3 thanks for trying it out! now another problem will be the different settings 2022.3 and 6000 using (I'm not even talking about anything in between). I'll probably create separate folders for all and ask users to copy corresponding one. Ugly but can't think of anything else.
<img width="200" alt="Image" src="https://github.com/user-attachments/assets/928031a6-965a-4a89-bdd4-88d28d2cd4f2" />

1) this sounds like it might be serious, I would love to learn more about this. First load might be slow I guess because it will be downloading everything from server and not using cache.
Also I'm trying to merge all small fixes into 3.0.2 these days and that might help too.
2) is this about the `launcherTemplate.gradle` change? I wasn't aware it's any different than 'mainTemplate.gradle`

Duplicate class problem is interesting. looks like we have it in one of our core libraries but somehow it's not a problem if you are building with 2022.3 but it's now a duplicate you need to handle if you are building with 6000.

**Comment by Jacki3** [comment]
Separate folders seems like the best solution for the time being I guess! This is why the plugin requires updating rather than changing build files (it is a classic "Unity problem" as we have no control on what they do during updates and how this breaks our old code). 

1. I feel as though it is a teething issue you will face when rebuilding your plugin and tools - if you want me to test anything further then I am happy to help - feel free to give me an email or DM.
2. In the past when I have updated launcher settings, you can often prevent the app from being allowed to launch or android requires the app to be scanned (which looks rather sus for players). Regarding the differences between specific gradle files and settings I could not give you a comprehensive/accurate answer.

**To help with the investigation:**
There is an issue with the public release of the Mapbox plugin (not this one in question) and Unity 6. The key difference between my 2022 and 2025 versions was the application's 'entry point settings' in the Player Settings where in 2022 it was common for this to be 'Activity' and in Unity 6 it was typical to be new version 'GameActivity'.  It appears app.Activity is more forgiving and is not so focused on AndroidX but I am no expert - there are clearly some outdated aspects of the code that need updating to match new Android libraries and this is probably going to cause more headache the more Unity/Android updates!

edit, link for reference: https://docs.unity3d.com/2023.1/Documentation/Manual/android-application-entries.html
