### ISSUE TITLE
The signature of “MapboxCommon.xcframework” cannot be validated and may have been compromised

### ISSUE THREAD

**Issue by Ardoos** [mapbox/mapbox-unity-sdk#1945]
I've been developing app using sdk3 branch in Unity 2022.3.61f1. It has worked earlier, but suddenly I can't build because of this error. I didn't make any changes to the Mapbox framework although I tried to pull new commits just to check if it helps. I have same issue on second Macbook, even getting second error with Turf framework. 

<img width="260" height="276" alt="Image" src="https://github.com/user-attachments/assets/4d1b119d-74c8-4ae6-86a1-ce7356411293" />

**Comment by frozenmistadventure** [comment]
I got the same error today and found a temporary fix by removing the pre-embedded signatures.
```
cd path/to/MapboxCommon.xcframework

find . -name "CodeSignature" -type d -exec rm -rf {} +
find . -name "_CodeSignature" -type d -exec rm -rf {} +
```


> I've been developing app using sdk3 branch in Unity 2022.3.61f1. It has worked earlier, but suddenly I can't build because of this error. I didn't make any changes to the Mapbox framework although I tried to pull new commits just to check if it helps. I have same issue on second Macbook, even getting second error with Turf framework.
> 
> <img alt="Image" width="260" height="276" src="https://private-user-images.githubusercontent.com/17052083/465752777-4d1b119d-74c8-4ae6-86a1-ce7356411293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0NjQ2MTcsIm5iZiI6MTc1MjQ2NDMxNywicGF0aCI6Ii8xNzA1MjA4My80NjU3NTI3NzctNGQxYjExOWQtNzRjOC00YWU2LTg2YTEtY2U3MzU2NDExMjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDAzMzgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOWNkZjAwODA1ZmViYjg2ZjFmZjFkYzkzMDNlMDUwMWIxYzIzYTcxNDBhOTZhMTQwOWFkYzE0Y2NhMTZhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yuHoIsfRtUMvlBNcKr0w2EJgap__bjRBNIGT3GpCVKE">

**Comment by Ardoos** [comment]
Thanks, it works! I suppose this is not expected to get past through AppStore checks?

**Comment by frozenmistadventure** [comment]
> Thanks, it works! I suppose this is not expected to get past through AppStore checks?

It's possible to sign your own apple id.
This is the first time I got this error, not sure if Apple Policy allowed or not.

My other project will submit to App Store by the end of this month, hopefully the certificate won't affect the submission.
If you have a chance to verify it sooner, please let me know as well.

```
cd path/to/MapboxCommon.xcframework

find . -name "CodeSignature" -type d -exec rm -rf {} +
find . -name "_CodeSignature" -type d -exec rm -rf {} +

find . -name "*.framework" -type d | while read FRAMEWORK; do
  codesign --force --timestamp=none --sign "YourDeveloperName" "$FRAMEWORK"
done 
```

**Comment by Ardoos** [comment]
So far I'm still stuck debugging this issuse. My app game alos use AR Foundation framework. It seems that removing signatures allows building an app, but it triggers error in AR Package. Re-signing it with my apple id doesn't help.
I'm pretty sure it has to do something with Mapbox and signatures as AR starts to work as soon as I remove Mapbox package from the project.

**Comment by frozenmistadventure** [comment]
> So far I'm still stuck debugging this issuse. My app game alos use AR Foundation framework. It seems that removing signatures allows building an app, but it triggers error in AR Package. Re-signing it with my apple id doesn't help. I'm pretty sure it has to do something with Mapbox and signatures as AR starts to work as soon as I remove Mapbox package from the project.

AR foundation should be Unity's package? What's your other packages errors?
In my case, I can deploy the app with/without re-signing it, only using the map feature + Vuforia in my project.

Hopefully Mapbox's developers will check this post and push some updates asap...

**Comment by Ardoos** [comment]
I'm using Ar Foundation 5.2.0, it's' Unity's package, alongside with XR dependency packages.

I compared logs for game with and without mapbox package, I don't see any important logs/errors that appear only in one version. Somehow for version with MapBox I see black screen for split second and then it disappears, like it can't initialize camera. If I remove MapBox, same scene works perfectly fine.

**Comment by brnkhy** [comment]
Hey @Ardoos, I noticed you mentioned pulling new commits in your first message. do you which commit you were before? I think our last changes to platform specific libraries was in late january and early feburary so I'm wondering if it's related to them.

**Comment by Ardoos** [comment]
Hey @brnkhy, I don't think this issue is related to any recent changes. As I mentioned before, I'm using sdk3 branch. At first I pulled in first day of May (2/3 May probably). I didn't pull any new commits until signature bug occured. Updating to current sdk3 commit didn't break build, it was performed because issue has risen and I tried to fix it.

**Comment by Ardoos** [comment]
@brnkhy any progress on the case?

**Comment by brnkhy** [comment]
@Ardoos turns out this is a general issue with one of our core libraries and there's a fix released. I'll update to the latest version and if everything goes well, will share it with you as soon as possible.

**Comment by brnkhy** [comment]
@Ardoos @frozenmistadventure 
I pushed the new libraries on branch `commonLibIosUpdate`. Did a test build and it worked fine but you are more familiar with the issue so I'm looking forward to hear from you. hope this fixes the issue.

**Comment by Ardoos** [comment]
In sdk3 branch I've replaced content of Runtime\Mapbox\BaseModule\Plugins\iOS with `commonLibIosUpdate` version. Reimported whole package in Unity, removed & cleaned xCode project, but it throws same error with `MapboxCommon.xcframework`, there is also new one, same error but `Turf.xcframework`. 
@frozenmistadventure can you check if that fix works for you?

**Comment by brnkhy** [comment]
@Ardoos oh I wasn't expecting that. I'll need to take another look, I don't remember seeing anything about Turf but I'll check that as well. I might not be able to next two days though but I'll definitely try to get back to this before sunday.

**Comment by OdNairy** [comment]
The issue is caused by the accidental certificate revoke in the Mapbox Maps SDK. Here is the ticket to track:
- https://github.com/mapbox/mapbox-maps-ios/issues/2344

In the Mapbox Maps SDK (Swift) we've release a patch releases for every affected minor version so it should be fixed now. 
Unfortunately, I don't know much about the unity sdk. But I assume that it should be enough to bump the native Maps SDK version.

> there is also new one, same error but Turf.xcframework

@Ardoos could you elaborate on this one? I haven't seen Turf framework to be affected by the issue - only MapboxCommon and MapboxCoreMaps.

**Comment by OdNairy** [comment]
You also can use the following command to clean up codesigning:

```
codesign --remove-signature --deep MapboxCommon.xcframework
```

**Comment by MrJebara** [comment]
Deleting both Codesign files in MapboxCommon.xcframework and Turf.xcframework got it to work for me

**Comment by Ardoos** [comment]
@OdNairy Turf error appeared after updating unity mapbox sdk to `commonLibIosUpdate` branch. I can build if i clean up codesigning with your `--remove-signature` command for both MapboxCommon and Turf .xcframework.

This didn't solve my issue though. I just re-tested it to be sure. I deleted Mapbox package and my scripts based on Mapbox SDK. Everything related to scanning qr code works (XR + XXing.Net to interpret camera input). After I reimported mapbox package, deleted codesigning and rebuild app I lose camera input (screen is black).

@brnkhy how can I upgrade Native Mapbox SDK in Mapbox Unity package to test if this can fix my error?

**Comment by frozenmistadventure** [comment]
> [@OdNairy](https://github.com/OdNairy) Turf error appeared after updating unity mapbox sdk to `commonLibIosUpdate` branch. I can build if i clean up codesigning with your `--remove-signature` command for both MapboxCommon and Turf .xcframework.
> 
> This didn't solve my issue though. I just re-tested it to be sure. I deleted Mapbox package and my scripts based on Mapbox SDK. Everything related to scanning qr code works (XR + XXing.Net to interpret camera input). After I reimported mapbox package, deleted codesigning and rebuild app I lose camera input (screen is black).
> 
> [@brnkhy](https://github.com/brnkhy) how can I upgrade Native Mapbox SDK in Mapbox Unity package to test if this can fix my error?

Is it possible that the renderCam for mapbox overriding your MainCam? or blocking background webcam layer?
In my own use case, I didn't use their prefab or demo scene or example rig. And I didn't find any critical bug or error after removal the signature in this two weeks yet.

PS: just sharing my other experience related to XR black screen.
In my other project, related to XR or black screen issue, they are usually due to camera related issue.
- Depending on Vulkan or OpenGL Graphics APIs etc and also Unity version etc, URP or Built-in Pipeline etc, the camera may return frame buffer in either texture2D(Single) or texture2D Array(Stereo), and it may cause black screen issue if your shader didn't support texture2D Array.
- The shader UV vertex sampling quad sometimes could be flipped or in negative value, will also possible cause black screen.
- maybe Mapbox override your XR Graphics api settings, or XR render config?
- and sometimes enable/disable SplashScreen will trigger the frame buffer type changes in some Unity version, will cause black screen if your other camera shader didn't support, or other post-processing script etc.
- single-pass vs multi-pass stereo related topic as well.

**Comment by brnkhy** [comment]
@Ardoos `commonLibIosUpdate` has the library updates which should fix the signature error and I think you are over that part, is that correct?
Black camera must be a different and app specific issue. I'm afraid I don't have AR experience to help with that but I hope @frozenmistadventure's suggestions help (and thanks for those @frozenmistadventure!)

**Comment by Ardoos** [comment]
@frozenmistadventure was right, turns out the fix was as easy as adding AR renderer feature to URP that was deleted on mapbox import for some reason. Removing signature works for now, so case closed, thanks!

**Comment by brnkhy** [comment]
I think solution verified by multiple developers now so I'll merge that into main dev branch in next few days. Thank you very much all 🙇‍♂️

**Comment by OdNairy** [comment]
@brnkhy could you try to update the mapbox-maps-ios package first to confirm if the issue would gone? 
To the best of my knowledge, the signing issue must be gone since we re-released a bunch of maps/nav/search versions.

**Comment by brnkhy** [comment]
@OdNairy I think `mapbox-maps-ios` is another package, we are only using `MapboxCommon` in Unity SDK.

**Comment by AndrewGe** [comment]
@brnkhy  Curious whether you have merged the changes into the sdk3 branch yet? It looks like the timestamps for the files are still pointing to 3 months ago

**Comment by brnkhy** [comment]
@AndrewGe aah no I wasn't able to. I should have merged this in right away but I packed it into a bigger version along with other changes and now those other stuff giving me troubles, delaying the version. I'll probably release it this week though.

**Comment by brnkhy** [comment]
@AndrewGe I decided to not-include some other changes into the new version and merged the fixes into `sdk3`, not to delay it any further. thanks for the reminder!
