### ISSUE TITLE
Bug: "ArgumentException: path" when deleting cache

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#653]
I'm getting an "ArgumentException: path" when I try to delete cache through the Mapbox -> Clear Caches -> All menu. It started happening after upgrading to version 1.4.0. 

* Unity version: 2017.3.1f1
* Mapbox SDK version: 1.4.0
* The platform you're building to: Running in Editor only
* A description of what you're trying to do: Delete cache
* Steps to recreate the bug if appropriate: 
* Links to your logs are also helpful: 

Log from Console:
deleting \\?\C:\Users\jorra\AppData\LocalLow\Goontech AS\Syna\cache\mapbox.terrain-rgb.cache
0x00000001412F21A6 (Unity) StackWalker::GetCurrentCallstack
0x00000001412F2D1F (Unity) StackWalker::ShowCallstack
0x00000001411B0910 (Unity) GetStacktrace
0x00000001406DAF53 (Unity) DebugStringToFile
0x00000001406DB731 (Unity) DebugStringToFile
0x000000014142BB62 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000000004C29A570 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
0x000000004C29A44A (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x000000004C299E2B (Mono JIT Code) [Logger.cs:114] UnityEngine.Logger:LogFormat (UnityEngine.LogType,string,object[]) 
0x000000004C299B63 (Mono JIT Code) [DebugBindings.gen.cs:115] UnityEngine.Debug:LogFormat (string,object[]) 
0x000000004C298842 (Mono JIT Code) [MbTiles.cs:329] Mapbox.Platform.MbTiles.MbTilesDb:Delete () 
0x000000004C29842D (Mono JIT Code) [MbTilesCache.cs:176] Mapbox.Platform.Cache.MbTilesCache:Clear (string) 
0x000000004C297B54 (Mono JIT Code) [MbTilesCache.cs:164] Mapbox.Platform.Cache.MbTilesCache:Clear () 
0x000000004C297648 (Mono JIT Code) [CachingWebFileSource.cs:99] Mapbox.Platform.Cache.CachingWebFileSource:Clear () 
0x000000004C2973D7 (Mono JIT Code) [MapboxAccess.cs:132] Mapbox.Unity.MapboxAccess:ClearSceneCache () 
0x000000004C296E4A (Mono JIT Code) [MapboxAccess.cs:141] Mapbox.Unity.MapboxAccess:ClearAllCacheFiles () 
0x000000004C296D47 (Mono JIT Code) [ClearMbTilesCache.cs:23] Mapbox.Editor.ClearMbTilesCache:ClearAllCachFiles () 
0x000000004C4C298E (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FFE0903436A (mono-2.0-bdwgc) [mini-runtime.c:2620] mono_jit_runtime_invoke 
0x00007FFE09239567 (mono-2.0-bdwgc) [object.c:2853] do_runtime_invoke 
0x00007FFE09241F6F (mono-2.0-bdwgc) [object.c:2905] mono_runtime_invoke 
0x0000000140A2EF6C (Unity) scripting_method_invoke
0x0000000140A229AA (Unity) ScriptingInvocation::Invoke
0x0000000140A23A1E (Unity) ScriptingInvocation::InvokeChecked
0x0000000140C087B1 (Unity) ScriptCommands::InvokeMenuItemWithContext
0x0000000140C08A03 (Unity) ScriptCommands::Execute
0x000000014115E969 (Unity) MenuController::ExecuteMenuItem
0x000000014140F7FD (Unity) ProcessMainWindowMessages
0x00000001413FC308 (Unity) ContainerWindow::ContainerWndProc
0x00007FFE5358B85D (USER32) CallWindowProcW
0x00007FFE5358B1EF (USER32) DispatchMessageW
0x000000014140FE90 (Unity) MainMessageLoop
0x00000001414117AC (Unity) WinMain
0x0000000141E65728 (Unity) __tmainCRTStartup
0x00007FFE52DE1FE4 (KERNEL32) BaseThreadInitThunk
0x00007FFE5522EFC1 (ntdll) RtlUserThreadStart

Error from Console: 
ArgumentException: path
System.IO.Path.Validate (System.String path, System.String parameterName) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.IO.Path.Validate (System.String path) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.IO.File.Delete (System.String path) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
Mapbox.Platform.MbTiles.MbTilesDb.Delete () (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs:347)
Mapbox.Platform.Cache.MbTilesCache.Clear (System.String mapId) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:175)
Mapbox.Platform.Cache.MbTilesCache.Clear () (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs:163)
Mapbox.Platform.Cache.CachingWebFileSource.Clear () (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:98)
Mapbox.Unity.MapboxAccess.ClearSceneCache () (at Assets/Mapbox/Unity/MapboxAccess.cs:131)
Mapbox.Unity.MapboxAccess.ClearAllCacheFiles () (at Assets/Mapbox/Unity/MapboxAccess.cs:139)
Mapbox.Editor.ClearMbTilesCache.ClearAllCachFiles () (at Assets/Mapbox/Unity/Editor/ClearMbTilesCache.cs:22)

**Comment by JorgenEngenNapstad** [comment]
Also, when I tried to delete the cache from the path in the log above manually, I'm still having an issue where some tiles are still having the previous map style (I modified my custom map, but it's still the same MapId).

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad that's a strange error.

Any chance you already had manually deleted `mapbox.terrain-rgb.cache` and Unity was still running when above error occured?

If you manually delete caches you'd have to
* close Unity
* delete `<YOUR-MAP-ID>.cache` file in `C:\Users\jorra\AppData\LocalLow\Goontech AS\Syna\cache\`  just `mapbox.terrain-rgb.cache`

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS That might have happened. But I get it even if I delete both cache files manually, restart Unity, and then try to delete the cache again.

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS Sorry for the late reply. Here is the log file. 

[Editor.log](https://github.com/mapbox/mapbox-unity-sdk/files/1898982/Editor.log)

**Comment by BergWerkGIS** [comment]
@JorgenEngenNapstad thanks for the log file.

Finally I'm able to reproduce the issue.
You are using the `Experimental (.NET 4.6 Equivalent)` scripting runtime and that's causing the issue.
Works with the default `Stable (.NET 3.5 Equivalent)`.

I'll look into it.

**Comment by BergWerkGIS** [comment]
Hm, that looks like a bug in the experimental runtime to me - also tried with `Unity@2018.1.0b13` - same error.

@JorgenEngenNapstad commenting this line should fix it for you till I figure out a proper solution:

https://github.com/mapbox/mapbox-unity-sdk/blob/db2468047e6a83bd7c21a1a5f3481427102fe06e/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/MbTiles/MbTiles.cs#L154

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS Thanks, that took care of the error. 

I'm still having cache issues though. After I use Clear Caches -> All or Current Scene, I'm seeing tiles in two different styles like in the image below:

![image](https://user-images.githubusercontent.com/35730930/38630143-5cb330f0-3db6-11e8-8be4-ed42dcbe9296.png)

**Comment by BergWerkGIS** [comment]
> Tiles from an old version of the map are still being loaded, even if the cache is cleared..

Even after `Stop` and `Play`?

Clearing caches only affects the files on disk not the already created Unity objects.

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS The tile problem actually disappeared.. I'm not sure what fixed it. But it's still not being cleared.. I have tried deleting the cache from the editor while not in Play mode, while in Play mode (then pressing Stop and Play again), deleting the cache files locally and restarted my PC, and I'm still getting an old version of the map.. I'm super confused.

**Comment by BergWerkGIS** [comment]
> The only difference from before is that now it's loading the wrong (old) map across all tiles.

Oh wow, that's super weird.

----

Any chance that somehow your style got reverted to an old version by accident on https://www.mapbox.com/studio/ ?

---- 

If your Studio style is correct please try this:
* `Play`
* `Mapbox -> Clear Caches -> All`
*  `Stop`
* `Mapbox -> Setup -> Configuration`:
![image](https://user-images.githubusercontent.com/4549888/38914943-130efe3a-42e2-11e8-820c-2c327fddf745.png)
  * set `Mem Cache Size` and `MBTiles Cache Size` to `0`
  * `Save`
* restart Unity
* `Play`

**Do you see new or old tiles?**

----

There's another setting intended _for development_ when map styles are changing frequently:
![image](https://user-images.githubusercontent.com/4549888/38915290-74ab8f4a-42e3-11e8-8890-9288e1089843.png)

But it's advised to not use it in production as it fires webrequests for each tile even it is in the local cache (to check if a newer version is available).

**Do you see new or old tiles?**

-----

If nothing of the above helps could you provide another set of `Editor.log` and `Editor-prev.log` that I can take a another look.

**Comment by JorgenEngenNapstad** [comment]
I tried the first solution, and that gave me a mix of old and new tiles again. I also have the old tiles in some zoom levels, and the new ones in others:
![image](https://user-images.githubusercontent.com/35730930/38919359-a86a080e-42f0-11e8-9644-208f675d18e9.png)

Whats also weird is that I'm using the mapbox-terrain-rgb layer in Mapbox Studio, but that does not show up at all in the Raster image texture in Unity.. (have I missed something here?) 
![image](https://user-images.githubusercontent.com/35730930/38919451-ebcca6a6-42f0-11e8-9c12-67be53a02622.png)

**Comment by JorgenEngenNapstad** [comment]
Updated Editor logs are attached. 
[Editor-prev.log](https://github.com/mapbox/mapbox-unity-sdk/files/1923060/Editor-prev.log)
[Editor.log](https://github.com/mapbox/mapbox-unity-sdk/files/1923061/Editor.log)

**Comment by BergWerkGIS** [comment]
hm, this getting weirder every time ☹️ 

Maybe you are connected via a proxy that caches stuff too?

> Whats also weird is that I'm using the mapbox-terrain-rgb layer in Mapbox Studio, but that does not show up at all in the Raster image texture in Unity.. (have I missed something here?)

you should be set.

> Updated Editor logs are attached.

Sorry If I wasn't explicit enough before but you'd have to `Play` your scene before copying the log files.
Both of them just contain information about Unity starting up and shutting down - nothing else.

Could you provide a new set of log files after you've played your scene?

Are you using the custom ` MbTiles.cs` I provided for you [above](https://github.com/mapbox/mapbox-unity-sdk/issues/653#issuecomment-379672110)?

**Comment by JorgenEngenNapstad** [comment]
It might have been reverted.. I replaced it with the one you sent now, and commented out line 138 ( _dbPath = Path.GetFullPath(@"\\?\" + _dbPath); )

I cleared All Cache in Play mode, and the is the resulting logs (Had to zip because of size):

[EditorLogs.zip](https://github.com/mapbox/mapbox-unity-sdk/files/1924049/EditorLogs.zip)

**Comment by JorgenEngenNapstad** [comment]
@BergWerkGIS I'm afraid we have to stick with `Experimental .NET 4.6`. 

It's okay. We will try to look into it a bit more ourselves first.
