### ISSUE TITLE
Map Image Factory fails to load first tile

### ISSUE THREAD

**Issue by utkarshdwivedi3997** [mapbox/mapbox-unity-sdk#706]
I'm using a map image factory to render tiles (along with a custom factory for spawning prefabs, a map building factory and a flat terrain factory). When I start the build of the game (either in Editor or an Android or iOS device), the first tile usually fails to load the image factory. Everything else - the custom prefabs and the build meshes etc., - loads for every tile. It's just the images for the first tile that don't load.

I'm using a CameraBoundsTileProvider to load the tiles.

I've tried switching Map Type and Style in the MapImageFactory inspector, but nothing seems to work.
The confusing part is that the image seems to load sometimes, but that's rather rare. Also, I switched the "loading" texture to be something other than the default grid, but all loading tiles still show the grid.

The game relies heavily on GPS, and not being able to see the map is not good. Is there a way to fix this? Also please let me know if I can provide more information.

Unity version: 2017.1.3f
Mapbox SDK version: 1.3.0
Platform: Android / iOS

**Comment by utkarshdwivedi3997** [comment]
The zoom level is 17 and the location is around (39.957425, -75.190921).
The TileErrorHandler didn't catch any exception for me, unfortunately.

**Comment by utkarshdwivedi3997** [comment]
The zoom level is 17 and the location is around (39.957425, -75.190921).
I get a request aborted error on all tiles on screen EXCEPT for the ones that do not load. The ones that don't load seem to not even cause any exception - it's like the system forgets about them totally. I'm not really sure what's causing it.

**Comment by atripathi-mb** [comment]
@utkarshdwivedi3997 Would it be possible for you to put a screenshot of your map settings? 

> I get a request aborted error on all tiles on screen EXCEPT for the ones that do not load.

Please share the error and the call stack. 

> clearing the cache helps the tiles to load the first time after clearing, but then the issue returns.

Once the tiles are cached, they are loaded from the cache instead of requesting them from the web. Are you using the `Experimental Runtime .Net 4.6` by any chance?

**Comment by atripathi-mb** [comment]
@utkarshdwivedi3997 I just realized you are using v1.3.0 of the SDK. We just released v1.4.1 , any chance you can update to the latest SDK and see if the issue exists?

**Comment by utkarshdwivedi3997** [comment]
Yes, here's the two frequent errors I'm getting on the tiles:

`2 Exception(s) caused on the tile. Tile ID:17/38165/49640 Tile Type:Mapbox.Map.VectorTile
Request aborted
Status Code 0
UnityEngine.Debug:LogWarning(Object)
Mapbox.Unity.Map.TileErrorHandler:_OnTileErrorHandler(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/TileErrorHandler.cs:48)
Mapbox.Unity.Map.AbstractMapVisualizer:Factory_OnTileError(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:233)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:72)
Mapbox.Unity.MeshGeneration.Factories.VectorTileFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:133)
Mapbox.Unity.MeshGeneration.Factories.<OnRegistered>c__AnonStorey0:<>m__0() (at Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:99)
Mapbox.Map.Tile:HandleTileResponse(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:231)
Mapbox.Platform.Cache.<Request>c__AnonStorey0:<>m__0(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:160)
Mapbox.Unity.Utilities.<DoRequest>c__Iterator0:MoveNext() (at Assets/Mapbox/Unity/Utilities/HTTPRequest.cs:65)
Mapbox.Unity.Utilities.Routine:MoveNext() (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

and

`2 Exception(s) caused on the tile. Tile ID:17/38164/49637 Tile Type:Mapbox.Map.RasterTile
Request aborted
Status Code 0
UnityEngine.Debug:LogWarning(Object)
Mapbox.Unity.Map.TileErrorHandler:_OnTileErrorHandler(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/TileErrorHandler.cs:48)
Mapbox.Unity.Map.AbstractMapVisualizer:Factory_OnTileError(Object, TileErrorEventArgs) (at Assets/Mapbox/Unity/Map/AbstractMapVisualizer.cs:233)
Mapbox.Unity.MeshGeneration.Factories.AbstractTileFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/AbstractTileFactory.cs:72)
Mapbox.Unity.MeshGeneration.Factories.MapImageFactory:OnErrorOccurred(TileErrorEventArgs) (at Assets/Mapbox/Unity/MeshGeneration/Factories/MapImageFactory.cs:116)
Mapbox.Unity.MeshGeneration.Factories.<OnRegistered>c__AnonStorey0:<>m__0() (at Assets/Mapbox/Unity/MeshGeneration/Factories/MapImageFactory.cs:98)
Mapbox.Map.Tile:HandleTileResponse(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:231)
Mapbox.Platform.Cache.<Request>c__AnonStorey0:<>m__0(Response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:160)
Mapbox.Unity.Utilities.<DoRequest>c__Iterator0:MoveNext() (at Assets/Mapbox/Unity/Utilities/HTTPRequest.cs:65)
Mapbox.Unity.Utilities.Routine:MoveNext() (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

**Comment by utkarshdwivedi3997** [comment]
@atripathi-mb 
Here's the settings for the map:

![mapsettings](https://user-images.githubusercontent.com/22533563/39152489-91d012f8-4716-11e8-8f37-e4216a210c67.PNG)

The MapImageFactory:

![mapimagefactory](https://user-images.githubusercontent.com/22533563/39152582-d424fbd2-4716-11e8-8e7c-cc8950ee1406.PNG)

and the main Mapbox configuration in Unity:

![config](https://user-images.githubusercontent.com/22533563/39152624-eef00f1a-4716-11e8-8a30-947930de0f85.PNG)


Also, yes I'll try updating the API as well.

**Comment by atripathi-mb** [comment]
@utkarshdwivedi3997 Do you get this error with the `Initialize Map with Location Provider` component  active ?

One thing to note - You need to have the `InitializeOnStart` toggle turned off if you are using the `Initialize Map with Location Provider` script. 

cc @BergWerkGIS do these errors ring a bell?

**Comment by utkarshdwivedi3997** [comment]
@atripathi-mb Updating the API didn't work.
@BergWerkGIS I tried doubling, tripling and even increasing the web request timeout to like 10000. It doesn't work either.

One thing I figured helps is disabling the VectorTileFactory that is responsible for creating buildings. The first few tiles still fail to load, but it is much less frequent. They load much more often if there's no meshes for buildings being generated. Does this help you guys narrow down the issue?

**Comment by jordy-isaac** [comment]
@utkarshdwivedi3997 Thanks for writing back. Could you screen cap a video of what's happening? This will help us get a better idea of what's going on with the tiles.

**Comment by atripathi-mb** [comment]
@utkarshdwivedi3997 Also, here is a guide for migrating from v1.3 to v1.4+ https://www.mapbox.com/unity-sdk/overview/migrate-version/

**Comment by utkarshdwivedi3997** [comment]
@jordy-isaac yes! Here's a link to the video: https://youtu.be/VaU9WAS783I
You'll notice that three tiles fail to load and show the default loading-grid texture that comes with the mapbox sdk (this is important because I changed the loading texture to a different one). I then move the character around to unload those tiles, and then bring the character back, and this time the tiles load properly.

@atripathi-mb thanks a lot for this guide!

That said, I think I was able to fix the issue. I tried to use one of the other MapVisualizers that came as part of one of the example scenes with mapbox, and those ones worked. So I tried to see what I was doing differently, and the order in which I had placed my factories was different. Placing the terrain factory before placing the image factory helped solve the issue. I'm still not sure if this is the actual issue, but it might just be, because I've been testing it extensively, and it seems to have fixed the issue. I think this was one of the things mentioned in the getting started tutorials that I may have simply overlooked.
